smtp_config:
  smtp_server: smtp.gmail.com
  smtp_port: 465
  sender: mail@gmail.com
  password: password

twillio_config:
  account_sid: "sid" # switch with real one
  auth_token: "token" # switch with real one
  from_number: "+123456" # caller number switch with real one
  
